In [10]:
import numpy as np

import os 

os.getcwd()


'/Users/calvinsmith/Documents/GitHub/DIT867/pa4'

In [20]:
from scipy.linalg.blas import ddot
from scipy.linalg.blas import dscal

x = np.array(7)
y = np.array([6,7,8,5])

print(ddot(x,y))

print(np.dot(x,y))

print(x.dot(y))

print(dscal(x,y))

42.0
[42 49 56 35]
[42 49 56 35]
[42. 49. 56. 35.]


In [22]:
print(y)

[6 7 8 5]


In [1]:
## Implementing the SCV pegasos algorithm

from aml_perceptron import Pegasos

execfile('doc_classification.py')

Training time: 3.43 sec.
Accuracy: 0.8212.


In [1]:
# Implementing the LR pegasos algorithm

from aml_perceptron import Pegasos_LR

execfile('doc_classification.py')

/Users/calvinsmith/Documents/GitHub/DIT867/pa4/aml_perceptron.py:221: RuntimeWarning: overflow encountered in exp
  loss = -(y*x)/(1+ np.exp(y*score))


19137.566795077015
18709.417191911914
18457.48519937753
18283.82430477067
18150.173380167827
18040.5756327325
17952.181747943923
17876.18314050568
17811.206512756224
17752.767853883895
Training time: 6.53 sec.
Accuracy: 0.6756.


In [ ]:
# implementing SVC pegasos algorithm with BLAS function 
from aml_percetron import Pegasos

exec